window.worksData = [
  {
    id: "cat-returns",
    title: "고양이의보은 猫の恩返し",
    year: "2002",
    type: "DUMMY.",
    href: "./works/cat-returns.html",
    image: "./assets/images/cat-returns-cover.jpg",
  },
  {
    id: "monster",
    title: "괴물 怪物",
    year: "2023",
    type: "DUMMY.",
    href: "./works/monster.html",
    image: "./assets/images/monster-cover.jpg",
  },
  {
    id: "troll-factory",
    title: "댓글부대 Troll Factory",
    year: "2023",
    type: "DUMMY.",
    href: "./works/troll-factory.html",
    image: "./assets/images/troll-factory-cover.jpg",
  },
  {
    id: "the-fall",
    title: "더폴 The Fall",
    year: "2006",
    type: "DUMMY.",
    href: "./works/the-fall.html",
    image: "./assets/images/the-fall-cover.jpg",
  },
  {
    id: "color-of-pomegranates",
    title: "석류의 빛깔 The Color of Pomegranates",
    year: "1969",
    type: "DUMMY.",
    href: "./works/color-of-pomegranates.html",
    image: "./assets/images/color-of-pomegranates-cover.jpg",
  },
  {
    id: "nobody-knows",
    title: "아무도모른다 誰も知らない",
    year: "2004",
    type: "DUMMY.",
    href: "./works/nobody-knows.html",
    image: "./assets/images/nobody-knows-cover.jpg",
  },
  {
    id: "shortcomings",
    title: "완벽하지않아 Shortcomings",
    year: "2023",
    type: "DUMMY.",
    href: "./works/shortcomings.html",
    image: "./assets/images/shortcomings-cover.jpg",
  },
  {
    id: "challengers",
    title: "챌린저스 Challengers",
    year: "2023",
    type: "DUMMY.",
    href: "./works/challengers.html",
    image: "./assets/images/challengers-cover.jpg",
  },
  {
    id: "atypical-family",
    title: "히어로는 아닙니다만 The Atypical Family",
    year: "2024",
    type: "DUMMY.",
    href: "./works/atypical-family.html",
    image: "./assets/images/atypical-family-cover.jpg",
  },
];
